"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Action = void 0;
var Action;
(function (Action) {
    Action["addBundledTransactions"] = "addbundles";
    Action["addPublicAddresses"] = "addaddress";
    Action["burnAddress"] = "burnaddress";
    Action["newFundsRequest"] = "newfundsreq";
    Action["cancelFundsRequest"] = "cancelfndreq";
    Action["rejectFundsRequest"] = "rejectfndreq";
    Action["recordObt"] = "recordobt";
    Action["regAddress"] = "regaddress";
    Action["regDomain"] = "regdomain";
    Action["regDomainAddress"] = "regdomadd";
    Action["removeAddress"] = "remaddress";
    Action["removeAllAddresses"] = "remalladdr";
    Action["renewAddress"] = "renewaddress";
    Action["renewDomain"] = "renewdomain";
    Action["setDomainPublic"] = "setdomainpub";
    Action["transferAddress"] = "xferaddress";
    Action["transferDomain"] = "xferdomain";
    Action["transferTokensKey"] = "trnsfiopubky";
    Action["transferLockedTokens"] = "trnsloctoks";
    Action["wrapTokens"] = "wraptokens";
    Action["wrapDomain"] = "wrapdomain";
    Action["unstake"] = "unstakefio";
    Action["stake"] = "stakefio";
    Action["linkAuth"] = "linkauth";
    Action["updateAuth"] = "updateauth";
    Action["addNft"] = "addnft";
    Action["addPerm"] = "addperm";
    Action["voteProducer"] = "voteproducer";
    Action["updateCryptKey"] = "updcryptkey";
    Action["voteProxy"] = "voteproxy";
    Action["unwrapTokens"] = "unwraptokens";
    Action["unwrapDomain"] = "unwrapdomain";
})(Action || (exports.Action = Action = {}));
//# sourceMappingURL=Action.js.map