"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EndPoint = void 0;
var EndPoint;
(function (EndPoint) {
    EndPoint["newFundsRequest"] = "new_funds_request";
    EndPoint["registerFioAddress"] = "register_fio_address";
    EndPoint["registerFioDomain"] = "register_fio_domain";
    EndPoint["renewFioDomain"] = "renew_fio_domain";
    EndPoint["renewFioAddress"] = "renew_fio_address";
    EndPoint["burnFioAddress"] = "burn_fio_address";
    EndPoint["transferFioAddress"] = "transfer_fio_address";
    EndPoint["transferFioDomain"] = "transfer_fio_domain";
    EndPoint["addPubAddress"] = "add_pub_address";
    EndPoint["removePubAddress"] = "remove_pub_address";
    EndPoint["removeAllPubAddresses"] = "remove_all_pub_addresses";
    EndPoint["setFioDomainPublic"] = "set_fio_domain_public";
    EndPoint["rejectFundsRequest"] = "reject_funds_request";
    EndPoint["recordObtData"] = "record_obt_data";
    EndPoint["transferTokens"] = "transfer_tokens_pub_key";
    EndPoint["cancelFundsRequest"] = "cancel_funds_request";
    EndPoint["transferLockedTokens"] = "transfer_locked_tokens";
})(EndPoint = exports.EndPoint || (exports.EndPoint = {}));
