"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EndPoint = void 0;
var EndPoint;
(function (EndPoint) {
    EndPoint["newFundsRequest"] = "new_funds_request";
    EndPoint["registerFioAddress"] = "register_fio_address";
    EndPoint["registerFioDomain"] = "register_fio_domain";
    EndPoint["renewFioDomain"] = "renew_fio_domain";
    EndPoint["renewFioAddress"] = "renew_fio_address";
    EndPoint["burnFioAddress"] = "burn_fio_address";
    EndPoint["transferFioAddress"] = "transfer_fio_address";
    EndPoint["transferFioDomain"] = "transfer_fio_domain";
    EndPoint["addBundledTransactions"] = "add_bundled_transactions";
    EndPoint["addPubAddress"] = "add_pub_address";
    EndPoint["removePubAddress"] = "remove_pub_address";
    EndPoint["removeAllPubAddresses"] = "remove_all_pub_addresses";
    EndPoint["setFioDomainPublic"] = "set_fio_domain_public";
    EndPoint["rejectFundsRequest"] = "reject_funds_request";
    EndPoint["recordObtData"] = "record_obt_data";
    EndPoint["transferTokens"] = "transfer_tokens_pub_key";
    EndPoint["cancelFundsRequest"] = "cancel_funds_request";
    EndPoint["availabilityCheck"] = "avail_check";
    EndPoint["cancelledFioRequests"] = "get_cancelled_fio_requests";
    EndPoint["getAbi"] = "get_raw_abi";
    EndPoint["getAddresses"] = "get_fio_addresses";
    EndPoint["getDomains"] = "get_fio_domains";
    EndPoint["getFee"] = "get_fee";
    EndPoint["getFioBalance"] = "get_fio_balance";
    EndPoint["getNames"] = "get_fio_names";
    EndPoint["getObtData"] = "get_obt_data";
    EndPoint["getPublicAddress"] = "get_pub_address";
    EndPoint["pendingFioRequests"] = "get_pending_fio_requests";
    EndPoint["sentFioRequests"] = "get_sent_fio_requests";
})(EndPoint = exports.EndPoint || (exports.EndPoint = {}));
