export enum EndPoint {
  newFundsRequest = 'new_funds_request',
  registerFioAddress = 'register_fio_address',
  registerFioDomain = 'register_fio_domain',
  renewFioDomain = 'renew_fio_domain',
  renewFioAddress = 'renew_fio_address',
  burnFioAddress = 'burn_fio_address',
  transferFioAddress = 'transfer_fio_address',
  transferFioDomain = 'transfer_fio_domain',
  addBundledTransactions = 'add_bundled_transactions',
  addPubAddress = 'add_pub_address',
  removePubAddress = 'remove_pub_address',
  removeAllPubAddresses = 'remove_all_pub_addresses',
  setFioDomainPublic = 'set_fio_domain_public',
  rejectFundsRequest = 'reject_funds_request',
  recordObtData = 'record_obt_data',
  transferTokens = 'transfer_tokens_pub_key',
  cancelFundsRequest = 'cancel_funds_request',

  availabilityCheck = 'avail_check',
  cancelledFioRequests = 'get_cancelled_fio_requests',
  getAbi = 'get_raw_abi',
  getAddresses = 'get_fio_addresses',
  getDomains = 'get_fio_domains',
  getFee = 'get_fee',
  getFioBalance = 'get_fio_balance',
  getNames = 'get_fio_names',
  getObtData = 'get_obt_data',
  getPublicAddress = 'get_pub_address',
  pendingFioRequests = 'get_pending_fio_requests',
  sentFioRequests = 'get_sent_fio_requests',
}
