"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TransferLockedTokensRequest = exports.CancelFundsRequestRequest = exports.PushRequest = exports.AddBundledRequest = exports.TransferFioAddressRequest = exports.TransferFioDomainRequest = exports.BurnFioAddressRequest = exports.RenewFioDomainRequest = exports.RenewFioAddressRequest = exports.MockRegisterFioNameRequest = exports.RegisterFioDomainAddressRequest = exports.RegisterFioDomainRequest = exports.RegisterFioAddressRequest = exports.TransferTokensRequest = exports.RecordObtDataRequest = exports.RejectFundsRequestRequest = exports.FundsRequestRequest = exports.SetFioDomainVisibilityRequest = exports.RemoveAllPublicAddressesRequest = exports.RemovePublicAddressesRequest = exports.AddPublicAddressesRequest = void 0;
var AddPublicAddressesRequest_1 = require("./AddPublicAddressesRequest");
Object.defineProperty(exports, "AddPublicAddressesRequest", { enumerable: true, get: function () { return AddPublicAddressesRequest_1.AddPublicAddressesRequest; } });
var RemovePublicAddressesRequest_1 = require("./RemovePublicAddressesRequest");
Object.defineProperty(exports, "RemovePublicAddressesRequest", { enumerable: true, get: function () { return RemovePublicAddressesRequest_1.RemovePublicAddressesRequest; } });
var RemoveAllPublicAddressesRequest_1 = require("./RemoveAllPublicAddressesRequest");
Object.defineProperty(exports, "RemoveAllPublicAddressesRequest", { enumerable: true, get: function () { return RemoveAllPublicAddressesRequest_1.RemoveAllPublicAddressesRequest; } });
var SetFioDomainVisibilityRequest_1 = require("./SetFioDomainVisibilityRequest");
Object.defineProperty(exports, "SetFioDomainVisibilityRequest", { enumerable: true, get: function () { return SetFioDomainVisibilityRequest_1.SetFioDomainVisibilityRequest; } });
var FundsRequestRequest_1 = require("./FundsRequestRequest");
Object.defineProperty(exports, "FundsRequestRequest", { enumerable: true, get: function () { return FundsRequestRequest_1.FundsRequestRequest; } });
var RejectFundsRequestRequest_1 = require("./RejectFundsRequestRequest");
Object.defineProperty(exports, "RejectFundsRequestRequest", { enumerable: true, get: function () { return RejectFundsRequestRequest_1.RejectFundsRequestRequest; } });
var RecordObtDataRequest_1 = require("./RecordObtDataRequest");
Object.defineProperty(exports, "RecordObtDataRequest", { enumerable: true, get: function () { return RecordObtDataRequest_1.RecordObtDataRequest; } });
var TransferTokensRequest_1 = require("./TransferTokensRequest");
Object.defineProperty(exports, "TransferTokensRequest", { enumerable: true, get: function () { return TransferTokensRequest_1.TransferTokensRequest; } });
var RegisterFioAddressRequest_1 = require("./RegisterFioAddressRequest");
Object.defineProperty(exports, "RegisterFioAddressRequest", { enumerable: true, get: function () { return RegisterFioAddressRequest_1.RegisterFioAddressRequest; } });
var RegisterFioDomainRequest_1 = require("./RegisterFioDomainRequest");
Object.defineProperty(exports, "RegisterFioDomainRequest", { enumerable: true, get: function () { return RegisterFioDomainRequest_1.RegisterFioDomainRequest; } });
var RegisterFioDomainAddressRequest_1 = require("./RegisterFioDomainAddressRequest");
Object.defineProperty(exports, "RegisterFioDomainAddressRequest", { enumerable: true, get: function () { return RegisterFioDomainAddressRequest_1.RegisterFioDomainAddressRequest; } });
var MockRegisterFioNameRequest_1 = require("./MockRegisterFioNameRequest");
Object.defineProperty(exports, "MockRegisterFioNameRequest", { enumerable: true, get: function () { return MockRegisterFioNameRequest_1.MockRegisterFioNameRequest; } });
var RenewFioAddressRequest_1 = require("./RenewFioAddressRequest");
Object.defineProperty(exports, "RenewFioAddressRequest", { enumerable: true, get: function () { return RenewFioAddressRequest_1.RenewFioAddressRequest; } });
var RenewFioDomainRequest_1 = require("./RenewFioDomainRequest");
Object.defineProperty(exports, "RenewFioDomainRequest", { enumerable: true, get: function () { return RenewFioDomainRequest_1.RenewFioDomainRequest; } });
var BurnFioAddressRequest_1 = require("./BurnFioAddressRequest");
Object.defineProperty(exports, "BurnFioAddressRequest", { enumerable: true, get: function () { return BurnFioAddressRequest_1.BurnFioAddressRequest; } });
var TransferFioDomainRequest_1 = require("./TransferFioDomainRequest");
Object.defineProperty(exports, "TransferFioDomainRequest", { enumerable: true, get: function () { return TransferFioDomainRequest_1.TransferFioDomainRequest; } });
var TransferFioAddressRequest_1 = require("./TransferFioAddressRequest");
Object.defineProperty(exports, "TransferFioAddressRequest", { enumerable: true, get: function () { return TransferFioAddressRequest_1.TransferFioAddressRequest; } });
var AddBundledRequest_1 = require("./AddBundledRequest");
Object.defineProperty(exports, "AddBundledRequest", { enumerable: true, get: function () { return AddBundledRequest_1.AddBundledRequest; } });
var PushRequest_1 = require("./PushRequest");
Object.defineProperty(exports, "PushRequest", { enumerable: true, get: function () { return PushRequest_1.PushRequest; } });
var CancelFundsRequestRequest_1 = require("./CancelFundsRequestRequest");
Object.defineProperty(exports, "CancelFundsRequestRequest", { enumerable: true, get: function () { return CancelFundsRequestRequest_1.CancelFundsRequestRequest; } });
var TransferLockedTokensRequest_1 = require("./TransferLockedTokensRequest");
Object.defineProperty(exports, "TransferLockedTokensRequest", { enumerable: true, get: function () { return TransferLockedTokensRequest_1.TransferLockedTokensRequest; } });
